### PR TITLE
Add push notifications

### PR DESCRIPTION
**Pull request by arturomf94**
This PR will add the push notifications functionality to the app. 

So far only a test is working, that consists of the following: 

- The app checks whether notifications are available.
- The app asks for the user's consent.
- The registers a service worker (`service-worker.js`).
- The app creates a push notification subscription.
- The app sends the subscription to the push server.
- A button was added in the `/loadseed` route to test notifications.

To-do:

- [x] Customize notifications.
- [x] Enable notifications to be sent when a new message arrives.
- [x] Manage any errors with the permissions.
- [x] Change actions so as to redirect user to relevant route.

### CODE REVIEW

**Comment by arturomf94** [comment]
Notifications arrive (given that the user granted access) if a new message arrives. Issues so far: 

* Only the last message is displayed?
* Need to encrypt the content. 
* Notifications are sent even if the message has been sent by the user.

**Comment by arturomf94** [comment]
Notifications get get grouped by tag, so only the last message was being displayed... I changed that. Now each notification has its tag equal to the id of the message that is displayed. What do you think about this @MerlinB? 

Still need to fix the encryption of the content and send notifications only when the user is not on the app.

**Comment by arturomf94** [comment]
This PR is ready for review now. It now meets the requirements we talked about. Namely: 

* Redirects to chat on click. 
* Does not display message content. 
* Only works in the background. 

@MerlinB I see the build passed. Could you also have a look at this generally. If it's fine with you, then we're ready to merge.

**Comment by Vincents-github** [comment]
Thank you Arturo, will be detailing the next items here on Github.

**Comment by MerlinB** [comment]
I merged, but somehow Github doesn't recognize that.

**Comment by MerlinB** [comment]
All changes should be reflected here https://github.com/MerlinB/bob-sapper/commit/70d9a7f08c45755c2149db9b2e6a10749f5d552f

**Pull request closed without merging**
